import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * Decorative SVG Paddles
 * Visual elements for the main menu
 */
export function LeftPaddle() {
    return (_jsxs("svg", { width: "180", height: "360", viewBox: "0 0 180 360", fill: "none", xmlns: "http://www.w3.org/2000/svg", className: "opacity-60", children: [_jsxs("defs", { children: [_jsxs("linearGradient", { id: "leftGradient", x1: "0", y1: "0", x2: "1", y2: "1", children: [_jsx("stop", { offset: "0%", stopColor: "#ff6ec4", stopOpacity: "0.8" }), _jsx("stop", { offset: "100%", stopColor: "#7873f5", stopOpacity: "0.3" })] }), _jsxs("filter", { id: "leftGlow", x: "-50%", y: "-50%", width: "200%", height: "200%", children: [_jsx("feGaussianBlur", { stdDeviation: "8", result: "blur" }), _jsx("feBlend", { in: "SourceGraphic", in2: "blur" })] })] }), _jsx("rect", { x: "8", y: "20", rx: "20", ry: "20", width: "164", height: "320", fill: "url(#leftGradient)", opacity: "0.15" }), _jsx("rect", { x: "12", y: "24", rx: "18", ry: "18", width: "156", height: "312", fill: "none", stroke: "url(#leftGradient)", strokeWidth: "2", filter: "url(#leftGlow)" }), _jsxs("g", { transform: "translate(0, 60)", children: [_jsx("rect", { x: "28", y: "0", rx: "10", width: "124", height: "240", fill: "#0b0b1a", opacity: "0.4" }), _jsx("rect", { x: "36", y: "8", rx: "6", width: "108", height: "224", fill: "url(#leftGradient)", opacity: "0.08" })] })] }));
}
export function RightPaddle() {
    return (_jsxs("svg", { width: "180", height: "360", viewBox: "0 0 180 360", fill: "none", xmlns: "http://www.w3.org/2000/svg", className: "opacity-60", children: [_jsxs("defs", { children: [_jsxs("linearGradient", { id: "rightGradient", x1: "0", y1: "0", x2: "1", y2: "1", children: [_jsx("stop", { offset: "0%", stopColor: "#7873f5", stopOpacity: "0.8" }), _jsx("stop", { offset: "100%", stopColor: "#4facfe", stopOpacity: "0.3" })] }), _jsxs("filter", { id: "rightGlow", x: "-50%", y: "-50%", width: "200%", height: "200%", children: [_jsx("feGaussianBlur", { stdDeviation: "8", result: "blur" }), _jsx("feBlend", { in: "SourceGraphic", in2: "blur" })] })] }), _jsx("rect", { x: "8", y: "20", rx: "20", ry: "20", width: "164", height: "320", fill: "url(#rightGradient)", opacity: "0.15" }), _jsx("rect", { x: "12", y: "24", rx: "18", ry: "18", width: "156", height: "312", fill: "none", stroke: "url(#rightGradient)", strokeWidth: "2", filter: "url(#rightGlow)" }), _jsxs("g", { transform: "translate(0, 60)", children: [_jsx("rect", { x: "28", y: "0", rx: "10", width: "124", height: "240", fill: "#0b0b1a", opacity: "0.4" }), _jsx("rect", { x: "36", y: "8", rx: "6", width: "108", height: "224", fill: "url(#rightGradient)", opacity: "0.08" })] })] }));
}
